### ISSUE TITLE
Is there a way to add horizontal lines (upper or lower control limits) to the chart?

### ISSUE THREAD

**Issue by tylermanning** [anhoej/qicharts2#1]
I have calculated upper and lower control limits for an Xbar and Rbar charts, and using your package I can easily plot these with the control limits. However, I would like to add the upper and lower control limits to these graphs similar to the ones calculated and found here https://en.wikipedia.org/wiki/X%CC%85_and_R_chart

Is there a way to do this?

**Comment by anhoej** [comment]
The Xbar and range chart is not included in qicharts2. Range charts are often preferred when sample sizes are small and calculations are done by hand. The Xbar and S chart can be used with all sample sizes, and when calculations are done by computer, there really is no need for the range charts.
