### ISSUE TITLE
Suggestion: Document difference between title = NULL and title = ""

### ISSUE THREAD

**Issue by md0u80c9** [anhoej/qicharts2#14]
Hi,

I'm using a Pareto chart in Shiny. The titling is being handled by the Box() function of shiny, so I want the box header to show the title and not the chart.

This is possible by just setting title = "". If title = NULL, then the variable name is used to produce 'Pareto chart of ....'

However, I don't think this is in the documentation - certainly it's not in ?Paretochart. I stumbled upon the solution by accident.

Could you consider adding it to the documentation when you next do any significant work on qicharts()?

**Comment by anhoej** [comment]
Thanks Andrew,

My fault. NULL is now allowed as title argument in paretochart. Please check and report.

**Comment by md0u80c9** [comment]
Thank you! I had assumed it was intentional and was just an undocumented feature! I’ll test it tonight hopefully!
