### ISSUE TITLE
xbar control limits disappear for large subgroup sizes

### ISSUE THREAD

**Issue by pwildenhain** [anhoej/qicharts2#16]
When I try to create an xbar chart, with a large N size, the control limits disappear from my chart

Here's the reproduced example from the [vignette](https://cran.r-project.org/web/packages/qicharts2/vignettes/qicharts2.html#xbar-and-s-charts-for-average-and-standard-deviation-of-patient-age)

```r
cabg <- cabg %>% 
  mutate(month = as.Date(cut(date, 'month')))

qic(month, age, data  = cabg, chart = "xbar")
```
![image](https://user-images.githubusercontent.com/35195136/51124358-21e6b800-17ec-11e9-899c-6ca7da268733.png)

However, when I scale up the data set, some of my control limits disappear
```r
cabg_big <- rbind(cabg, cabg, cabg, cabg, cabg)

qic(month, age, data  = cabg_big, chart = "xbar")
```
![image](https://user-images.githubusercontent.com/35195136/51124470-62463600-17ec-11e9-9ca2-0972649567a1.png)

I get this warning message: `In c4(n) : value out of range in 'gammafn'`. When I tested the `c4()` function, I saw that error message specifically occurs when n > 343

```r
> qicharts2:::c4(343)
[1] 0.9992693
> qicharts2:::c4(344)
[1] Inf
Warning message:
In qicharts2:::c4(344) : value out of range in 'gammafn'
```

Can you help me understand why this is happening?

**Comment by brndngrhm** [comment]
Would a potential solution be to use the log-gamma function for large sample sizes? See for example [this 
 thread](http://r.789695.n4.nabble.com/Implementation-of-gamma-function-for-large-number-td907460.html).

**Comment by anhoej** [comment]
Thanks, I'll look into it.

**Comment by anhoej** [comment]
Fixed on GitHub. Please test and report.

**Comment by pwildenhain** [comment]
Works perfect, thanks! Thanks for fixing this so quickly, I should've replied as quickly!
