### ISSUE TITLE
Add a return.data argument to qic()

### ISSUE THREAD

**Issue by pwildenhain** [anhoej/qicharts2#17]
I know you can already get the data from the plot with something  like this
```r
plot_data <- qic(...)$data
```

It would be quicker, especially if you _only need_ the data to have something like this
```r
plot_data <- qic(..., return.data = TRUE)
```
Returning the aggregated `data.frame`, without having to plot the data first. 

As far as implementation, possibly placing a early `return()` [here](https://github.com/anhoej/qicharts2/blob/master/R/qic.R#L246) right before the data gets plotted, if `return.data = TRUE` 

Looking forward to hearing your thoughts about this feature request 😄

**Comment by anhoej** [comment]
Thanks! I'll think about it. 

On a first thought, no, because it adds nothing but a new argument to qic(), which already has too many. When using $data the plot is not printed, and anyway you would most likely assign the output to a variable anyway.
