### ISSUE TITLE
If x.period is NULL, qic returns error message

### ISSUE THREAD

**Issue by lenakba** [anhoej/qicharts2#18]
When using time data and defining x.period, qic works just fine:
`library(qicharts2)`
`qic(x = date, y = los, data = cabg, x.period = "month", chart = "xbar")`

Also, you can run qic without specifying x.period:
`library(qicharts2)`
`qic(x = date, y = los, data = cabg, chart = "xbar")`

But if you define x.period as NULL, the qic command returns an error and the figure is not returned:

``` r
library(qicharts2)
qic(x = date, y = los, data = cabg, x.period = NULL, chart = "xbar")
#> Error in cut.POSIXt(x, breaks = x.period): invalid specification of 'breaks'
```
This is problematic when someone calls the qic-command in a function where x.period is defined as NULL by default.   

I think this can be solved by replacing `!missing` with `!is.null` in this part of the qic function:

``` r
if (inherits(x, c('Date', 'POSIXt'))) { 
x <- as.POSIXct(as.character(x), tz = 'UTC')    
if (!missing(x.period)) {   
x <- as.POSIXct(cut(x, breaks = x.period))  
 }  
}
```

**Comment by anhoej** [comment]
Fixed on GitHub. Please test and report back.

**Comment by pwildenhain** [comment]
Thanks for making this change, it's going to be a big help to my team who frequently use`qic()`. However, we exclusively use the latest CRAN version. Do you have an estimation for when the next CRAN release will be?

**Comment by anhoej** [comment]
No promises. But probably within a couple of weeks.
