### ISSUE TITLE
Change Text Size of Control Chart UCL and LCL and Mean?

### ISSUE THREAD

**Issue by Christopher-Ng** [anhoej/qicharts2#24]
Is there a way to change the font size for the UCL and the LCL in a control chart? I've looked into a few things, and this is likely my ggplot2 ignorance, but I can't seem to find the right geom_x setting to change the font size. Thanks.

**Comment by anhoej** [comment]
At the moment, font size for line labels is hard coded. I will consider changing this in the future.
