### ISSUE TITLE
Missing data points

### ISSUE THREAD

**Issue by NathanProudlove** [anhoej/qicharts2#35]
Apologies if I've missed something...
If this is real, it might be something you look at sometime:

When the X axis is time there can be missing datapoints, but we need to keep that placeholder for plots.
The 'i' chart copes with some points being NA, but 'c' treats NA as 0.

with thanks, Nathan

**Comment by anhoej** [comment]
I actually stumbled over this myself the other days. Thanks for the reminder. Fixed on GitHub. Please check and report.

**Comment by NathanProudlove** [comment]
yes thanks - that fixed it!

**Comment by NathanProudlove** [comment]
Hi Jacob

yes thanks - that fixed it! – I’ve posted that back on Github


Something else I’ve noticed – might be a naïve question):

I understand that in run charts points on the cl (median) are grey (col5) to indicate that ‘not useful’ for some calculations.
But this also happens on SPC charts for points on the cl (mean). Is this intentional?!
I think it doesn’t affect calculations.
It’s a rare occurrence, so I’ve only just noticed it!

The file attached is a small example, modifying a small set of your pressure ulcers data, where the mean (of the n.pu variable) is 24, and there is a datapoint of 24.

Best wishes,

Nathan

Dr Nathan Proudlove FORS | Senior Lecturer (Assoc Prof) | Health Management Group
Director, PgDip Leadership & Management in the Healthcare Sciences (NHS Higher Specialist Scientist Training Programme DClinSci)

Alliance Manchester Business School | The University of Manchester | Booth Street West | Manchester M15 6PB
Office: Room 7.048
***@***.******@***.***>

www.linkedin.com/in/nathanproudlove<http://www.linkedin.com/in/nathanproudlove/>
www.researchgate.net/profile/Nathan_Proudlove<http://www.researchgate.net/profile/Nathan_Proudlove>
https://scholar.google.co.uk/citations?user=pTPHj40AAAAJ&hl=en

www.mbs.ac.uk<http://www.mbs.ac.uk/>  Facebook<https://www.facebook.com/manchestermbs>  Google+<https://plus.google.com/+manchesterbusinessschool/posts>   LinkedIn<http://www.linkedin.com/edu/manchester-business-school-12712>   Twitter<https://twitter.com/MBSnews>   YouTube<https://www.youtube.com/manchestermbs>

**Comment by anhoej** [comment]
Yes, that is intentional. Runs analysis based on longest run and number of crossings is useful regardles of the type of chart as long as the distribution of datapoints around the centre line is expected to be random.

**Comment by NathanProudlove** [comment]
OK – thanks!

Best wishes,

Nathan

Dr Nathan Proudlove FORS | Senior Lecturer (Assoc Prof) | Health Management Group
Director, PgDip Leadership & Management in the Healthcare Sciences (NHS Higher Specialist Scientist Training Programme DClinSci)

Alliance Manchester Business School | The University of Manchester | Booth Street West | Manchester M15 6PB
Office: Room 7.048
***@***.******@***.***>

www.linkedin.com/in/nathanproudlove<http://www.linkedin.com/in/nathanproudlove/>
www.researchgate.net/profile/Nathan_Proudlove<http://www.researchgate.net/profile/Nathan_Proudlove>
https://scholar.google.co.uk/citations?user=pTPHj40AAAAJ&hl=en

www.mbs.ac.uk<http://www.mbs.ac.uk/>  Facebook<https://www.facebook.com/manchestermbs>  Google+<https://plus.google.com/+manchesterbusinessschool/posts>   LinkedIn<http://www.linkedin.com/edu/manchester-business-school-12712>   Twitter<https://twitter.com/MBSnews>   YouTube<https://www.youtube.com/manchestermbs>
