### ISSUE TITLE
using ggplot2 commands to format x and y axis

### ISSUE THREAD

**Issue by bharuch2** [anhoej/qicharts2#38]
Love the qichart2 package. Thank you for all your work.

I'm recent working on "p" chart over a series of years.
years are "double".
when I graph the qic chart, the x-axis shows decimals (e.g. 2015.2).

I was hoping to use ggplot2 package commands (https://scales.r-lib.org/index.html), or scale_x_continuous(label = scales::label_comma(accuracy = 1) (https://stackoverflow.com/questions/15622001/how-to-display-only-integer-values-on-an-axis-using-ggplot2) 
but I'm having figure out syntax for the qic() function to also respect ggplot.
-I thought it might be possible since per the documentation, I saw that qic() was based on ggplot.

Thank you.

**Comment by anhoej** [comment]
Hi bharuch2

Thank you for your interest in qicharts2. Could you please provide a minimal reproducible example including data and code together with an example of the desired output.

PS: have you tried making dates date or POSIX type rather than double?

**Comment by bharuch2** [comment]
thank you so much for your willingness. My google skills are better (or may lucky).

based on [this](https://stackoverflow.com/questions/48997106/how-to-use-qicharts2-and-ggplots2-together), and above...

I solved it by following

y <- qic (....)

y +
    scale_x_continuous(label = scales::label_number(accuracy = 1, big.mark = ""))
