### ISSUE TITLE
Exclude different points for different facets

### ISSUE THREAD

**Issue by bernatplandolit** [anhoej/qicharts2#41]
Is there a possibility to exclude different points for different facets? For example, if I select one of the posted examples:

qic(month, n,
    n        = days,
    data     = hospital_infections,
    facets   = infection ~ hospital,
    chart    = 'u',
    multiply = 10000,
    title    = 'Hospital infection rates',
    ylab     = 'Number of infections per 10.000 risk days',
    xlab     = 'Month')

And get this plot:
<img width="792" alt="Captura de pantalla 2023-03-29 a las 21 05 01" src="https://user-images.githubusercontent.com/40602121/228641941-0c3bcf4c-97aa-48f2-b1e2-9b5bdd3ff738.png">

I can define a random vector to remove points:

to_exclude <-  c(1:5, 10:12)

qic(month, n,
    n        = days,
    data     = hospital_infections,
    facets   = infection ~ hospital,
    chart    = 'u',
    multiply = 10000,
    title    = 'Hospital infection rates',
    ylab     = 'Number of infections per 10.000 risk days',
    xlab     = 'Month',
    exclude = to_exclude)

But then I get the numbers 1 to 5 and 10 to 12 removed from all the control charts:
<img width="791" alt="Captura de pantalla 2023-03-29 a las 21 08 09" src="https://user-images.githubusercontent.com/40602121/228642639-c9d9acb6-9c70-4935-b24e-1e775fc32f81.png">

Is there a possibility or a workaround to remove different points by referring them to the original dataset? Maybe it could be added by referring to a column of the dataset having a label '1' to remove '0' to use.

**Comment by anhoej** [comment]
Good question. The answer i no for the time being. I might consider adding this to future versions of qicharts2 (or -3 or -4).
