### ISSUE TITLE
notes overlap if close together

### ISSUE THREAD

**Issue by davandyke** [anhoej/qicharts2#42]
The notes function is great, though the notes overlap if labeled interventions are too close in days. Is it possible to automatically nudge the labels up or down instead of on same line so they are readable? See example attached.
![example](https://user-images.githubusercontent.com/32722948/234037740-2012a305-b238-4736-bc73-03885b7db368.png)

**Comment by anhoej** [comment]
Thanks for the suggestion. I agree that overlapping notes are an annoyance. However, I am unable to find a smart solution, that do no include more dependencies. I also think that qicharts2 has become a rather large beast that has far too many options that would have been better left to ggplot. If you can find a solution, please suggest some code to fix the problem.

In the mean time, I suggest you add notes in the form of letters or very short codes that are explained in the figure caption (caption argument).
